spring:
  config:
    import: optional:classpath:config/secrets.yaml, optional:file:./config/secrets.yaml #secrets.yaml 파일로 값 읽어오기
    activate:
      on-profile: prod # 'prod' 프로필이 활성화될 때만 이 설정이 적용됨

  data:
    redis:
      host: ${REDIS_HOST}
      password: ${REDIS_PASSWORD}

  security:
    oauth2:
      client:
        registration:
          google:
            # 배포 서버 도메인으로 변경
            redirect-uri: https://${YOUR_DOMAIN}:58080/login/oauth2/code/google
          naver:
            # 배포 서버 도메인으로 변경
            redirect-uri: https://${YOUR_DOMAIN}:58080/login/oauth2/code/naver