name: Dev Server CI

on:
  pull_request:
    branches: [ develop ]
  push:
    branches: [ develop, main, performance-test]

jobs:
  pr-test:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true # 서브모듈 가져오기 활성화
          token: ${{ secrets.PROJECT_REPO_TOKEN }} # repo에 접근가능한 token 획득

      - name: Update Submodule
        run: git submodule update --remote

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'
          
      - name: Check Test Success
        run: ./gradlew test
        
      - name: Check Gradle Build Success
        run: ./gradlew build -x test

  build-and-push:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: false
          token: ${{ secrets.PROJECT_REPO_TOKEN }} # repo에 접근가능한 token 획득

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: build without test
        run: ./gradlew clean build -x test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            jungil12532/nova-spring-app:latest
            jungil12532/nova-spring-app:${{ github.sha }}
          cache-from: type=registry,ref=jungil12532/nova-spring-app:buildcache
          cache-to: type=registry,ref=jungil12532/nova-spring-app:buildcache,mode=max

  # 다음으로 실행할 스크립트 파일을 호출
  deploy-trigger:
    needs: build-and-push
    if: github.event_name == 'push'
    # 중요: 호출할 파일 경로 (같은 레포지토리 내 .github/workflows 폴더)
    uses: ./.github/workflows/dev-cd.yml
    # 중요: 메인 파일의 Secrets를 서브 파일로 모두 넘겨줍니다.
    secrets: inherit