name: Dev Server CI/CD

on:
  pull_request:
    branches: [ develop ]
  push:
    branches: [ develop, feat/cicd ]

jobs:
  pr-test:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true # 서브모듈 가져오기 활성화
          token: ${{ secrets.PROJECT_REPO_TOKEN }} # repo에 접근가능한 token 획득

      - name: Update Submodule
        run: git submodule update --remote

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'
          
      - name: Check Test Success
        run: ./gradlew test
        
      - name: Check Gradle Build Success
        run: ./gradlew build -x test

  build-and-push:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: false
          token: ${{ secrets.PROJECT_REPO_TOKEN }} # repo에 접근가능한 token 획득

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: build without test
        run: ./gradlew clean build -x test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            jungil12532/nova-spring-app:latest
            jungil12532/nova-spring-app:${{ github.sha }}
          cache-from: type=registry,ref=jungil12532/nova-spring-app:buildcache
          cache-to: type=registry,ref=jungil12532/nova-spring-app:buildcache,mode=max

  deploy:
    needs: build-and-push # build-and-push job이 먼저 성공해야 depoly job 실행
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout for Secrets # secrets.yaml을 submodule에서 가져옴
        uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ secrets.PROJECT_REPO_TOKEN }}

      - name: Copy secrets to server via SCP # SCP로 secrets.yaml 파일을 서버로 전송
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          password: ${{ secrets.REMOTE_PASSWORD }}
          port: 22
          # 보낼 파일 위치 (GitHub Runner 기준)
          source: "src/main/resources/config/secrets.yaml"
          # 받을 서버 위치 (자동으로 폴더가 생성되지 않을 수 있으니, 미리 존재하면 좋음)
          target: "/home/${{ secrets.REMOTE_USER }}/nova-server/config"
          # 소스 경로의 앞부분(src/main/resources/config)을 잘라내고 파일만 target에 넣기 위함
          strip_components: 4

      - name: Deploy to Dev Server via SSH # SSH로 접속하여 도커 실행
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          password: ${{ secrets.REMOTE_PASSWORD }}
          port: 22
          script: |
            # 서버에 config 디렉토리가 없으면 생성 (SCP 오류 방지용 안전장치)
            mkdir -p /home/${{ secrets.REMOTE_USER }}/nova-server/config
            # 이미지를 저장할 호스트 폴더 생성
            mkdir -p /home/${{ secrets.REMOTE_USER }}/images
            
            # 기존 컨테이너 중지 및 삭제 (에러 무시)
            docker stop nova-app || true
            docker rm nova-app || true

            # 사용하지 않는 이미지 정리, new 이미지 pull
            docker image prune -f
            docker pull jungil12532/nova-spring-app:latest

            # 새 컨테이너 실행 (Volume 마운트 적용)
            docker run -d \
              --name nova-app \
              -p 58080:8080 \
              -e SPRING_PROFILES_ACTIVE=prod \
              -v /home/${{ secrets.REMOTE_USER }}/nova-server/config/secrets.yaml:/app/config/secrets.yaml \
              -v /home/${{ secrets.REMOTE_USER }}/images:/app/images \
              jungil12532/nova-spring-app:latest