name: Dev Server CI/CD

on:
  pull_request:
    branches: [ develop ]
  push:
    branches: [ develop, feat/cicd ]

jobs:
  pr-test:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true # 서브모듈 가져오기 활성화
          token: ${{ secrets.PROJECT_REPO_TOKEN }} # repo에 접근가능한 token 획득

      - name: Update Submodule
        run: git submodule update --remote

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'
          
      - name: Check Test Success
        run: ./gradlew test
        
      - name: Check Gradle Build Success
        run: ./gradlew build -x test

  build-and-push:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: false
          token: ${{ secrets.PROJECT_REPO_TOKEN }} # repo에 접근가능한 token 획득

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: build without test
        run: ./gradlew clean build -x test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            jungil12532/nova-spring-app:latest
            jungil12532/nova-spring-app:${{ github.sha }}
          cache-from: type=registry,ref=jungil12532/nova-spring-app:buildcache
          cache-to: type=registry,ref=jungil12532/nova-spring-app:buildcache,mode=max

  deploy:
    needs: build-and-push # build-and-push job이 먼저 성공해야 depoly job 실행
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout for Secrets # secrets.yaml을 submodule에서 가져옴
        uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ secrets.PROJECT_REPO_TOKEN }}

      # SCP로 secrets, docker-compose, prometheus 파일을 서버로 전송
      - name: Copy secrets to server via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          password: ${{ secrets.REMOTE_PASSWORD }}
          port: 22
          # 보낼 파일 위치 (GitHub Runner 기준)
          source: "docker/docker-compose.yml,docker/prometheus.yml,src/main/resources/config/secrets.yaml"
          # 받을 서버 위치
          target: "/home/${{ secrets.REMOTE_USER }}/nova-server"

      # SSH로 접속하여 Docker Compose 실행
      - name: Deploy to Dev Server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          password: ${{ secrets.REMOTE_PASSWORD }}
          port: 22
          script: |
            echo "작업 디렉토리로 이동"
            cd /home/${{ secrets.REMOTE_USER }}/nova-server
            
            echo "docker 관련 파일 정리"
            mv docker/docker-compose.yml ./docker-compose.yml
            mv docker/prometheus.yml ./prometheus.yml
            rm -rf docker 
            
            echo "secrets 파일 정리"
            mv src/main/resources/config/secrets.yaml ./secrets.yaml
            rm -rf src
            
            echo "[디버깅] 파일이 잘 왔는지 리스트 출력"
            echo "====== FILE LIST CHECK ======"
            ls -al
            echo "============================="
            
            echo "이미지를 저장할 폴더 생성"
            mkdir -p /home/${{ secrets.REMOTE_USER }}/images

            echo "최신 이미지 Pull"
            docker compose pull
            
            echo "컨테이너 강제 재생성 (이미지가 바뀌었으면 재시작됨)"
            docker compose up -d --force-recreate --remove-orphans
            
            echo "불필요한 이미지 정리"
            docker image prune -f